// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/signal_control/v1/events.proto

package signalcontrolv1

import (
	v1 "github.com/Vikasa2M/openits-models/pkg/proto/openits/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaultSeverity int32

const (
	FaultSeverity_FAULT_SEVERITY_INFO     FaultSeverity = 0
	FaultSeverity_FAULT_SEVERITY_WARNING  FaultSeverity = 1
	FaultSeverity_FAULT_SEVERITY_MINOR    FaultSeverity = 2
	FaultSeverity_FAULT_SEVERITY_MAJOR    FaultSeverity = 3
	FaultSeverity_FAULT_SEVERITY_CRITICAL FaultSeverity = 4
)

// Enum value maps for FaultSeverity.
var (
	FaultSeverity_name = map[int32]string{
		0: "FAULT_SEVERITY_INFO",
		1: "FAULT_SEVERITY_WARNING",
		2: "FAULT_SEVERITY_MINOR",
		3: "FAULT_SEVERITY_MAJOR",
		4: "FAULT_SEVERITY_CRITICAL",
	}
	FaultSeverity_value = map[string]int32{
		"FAULT_SEVERITY_INFO":     0,
		"FAULT_SEVERITY_WARNING":  1,
		"FAULT_SEVERITY_MINOR":    2,
		"FAULT_SEVERITY_MAJOR":    3,
		"FAULT_SEVERITY_CRITICAL": 4,
	}
)

func (x FaultSeverity) Enum() *FaultSeverity {
	p := new(FaultSeverity)
	*p = x
	return p
}

func (x FaultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_signal_control_v1_events_proto_enumTypes[0].Descriptor()
}

func (FaultSeverity) Type() protoreflect.EnumType {
	return &file_openits_signal_control_v1_events_proto_enumTypes[0]
}

func (x FaultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultSeverity.Descriptor instead.
func (FaultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{0}
}

type Source int32

const (
	Source_SOURCE_UNSPECIFIED Source = 0
	Source_SOURCE_SCHEDULE    Source = 1
	Source_SOURCE_OPERATOR    Source = 2
	Source_SOURCE_ADAPTIVE    Source = 3
	Source_SOURCE_PREEMPTION  Source = 4
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_SCHEDULE",
		2: "SOURCE_OPERATOR",
		3: "SOURCE_ADAPTIVE",
		4: "SOURCE_PREEMPTION",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_SCHEDULE":    1,
		"SOURCE_OPERATOR":    2,
		"SOURCE_ADAPTIVE":    3,
		"SOURCE_PREEMPTION":  4,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_signal_control_v1_events_proto_enumTypes[1].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_openits_signal_control_v1_events_proto_enumTypes[1]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{1}
}

type TsamEngagementState int32

const (
	TsamEngagementState_TSAM_ENGAGEMENT_STATE_UNSPECIFIED TsamEngagementState = 0
	TsamEngagementState_TSAM_ENGAGEMENT_STATE_DISABLED    TsamEngagementState = 1
	TsamEngagementState_TSAM_ENGAGEMENT_STATE_ADVISORY    TsamEngagementState = 2
	TsamEngagementState_TSAM_ENGAGEMENT_STATE_ACTIVE      TsamEngagementState = 3
	TsamEngagementState_TSAM_ENGAGEMENT_STATE_SUSPENDED   TsamEngagementState = 4
)

// Enum value maps for TsamEngagementState.
var (
	TsamEngagementState_name = map[int32]string{
		0: "TSAM_ENGAGEMENT_STATE_UNSPECIFIED",
		1: "TSAM_ENGAGEMENT_STATE_DISABLED",
		2: "TSAM_ENGAGEMENT_STATE_ADVISORY",
		3: "TSAM_ENGAGEMENT_STATE_ACTIVE",
		4: "TSAM_ENGAGEMENT_STATE_SUSPENDED",
	}
	TsamEngagementState_value = map[string]int32{
		"TSAM_ENGAGEMENT_STATE_UNSPECIFIED": 0,
		"TSAM_ENGAGEMENT_STATE_DISABLED":    1,
		"TSAM_ENGAGEMENT_STATE_ADVISORY":    2,
		"TSAM_ENGAGEMENT_STATE_ACTIVE":      3,
		"TSAM_ENGAGEMENT_STATE_SUSPENDED":   4,
	}
)

func (x TsamEngagementState) Enum() *TsamEngagementState {
	p := new(TsamEngagementState)
	*p = x
	return p
}

func (x TsamEngagementState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TsamEngagementState) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_signal_control_v1_events_proto_enumTypes[2].Descriptor()
}

func (TsamEngagementState) Type() protoreflect.EnumType {
	return &file_openits_signal_control_v1_events_proto_enumTypes[2]
}

func (x TsamEngagementState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TsamEngagementState.Descriptor instead.
func (TsamEngagementState) EnumDescriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{2}
}

type AdjustmentType int32

const (
	AdjustmentType_ADJUSTMENT_TYPE_UNSPECIFIED       AdjustmentType = 0
	AdjustmentType_ADJUSTMENT_TYPE_CYCLE_LENGTH      AdjustmentType = 1
	AdjustmentType_ADJUSTMENT_TYPE_SPLIT_ADJUSTMENT  AdjustmentType = 2
	AdjustmentType_ADJUSTMENT_TYPE_OFFSET_ADJUSTMENT AdjustmentType = 3
	AdjustmentType_ADJUSTMENT_TYPE_PHASE_EXTENSION   AdjustmentType = 4
	AdjustmentType_ADJUSTMENT_TYPE_PHASE_TRUNCATION  AdjustmentType = 5
	AdjustmentType_ADJUSTMENT_TYPE_PLAN_CHANGE       AdjustmentType = 6
	AdjustmentType_ADJUSTMENT_TYPE_OTHER             AdjustmentType = 7
)

// Enum value maps for AdjustmentType.
var (
	AdjustmentType_name = map[int32]string{
		0: "ADJUSTMENT_TYPE_UNSPECIFIED",
		1: "ADJUSTMENT_TYPE_CYCLE_LENGTH",
		2: "ADJUSTMENT_TYPE_SPLIT_ADJUSTMENT",
		3: "ADJUSTMENT_TYPE_OFFSET_ADJUSTMENT",
		4: "ADJUSTMENT_TYPE_PHASE_EXTENSION",
		5: "ADJUSTMENT_TYPE_PHASE_TRUNCATION",
		6: "ADJUSTMENT_TYPE_PLAN_CHANGE",
		7: "ADJUSTMENT_TYPE_OTHER",
	}
	AdjustmentType_value = map[string]int32{
		"ADJUSTMENT_TYPE_UNSPECIFIED":       0,
		"ADJUSTMENT_TYPE_CYCLE_LENGTH":      1,
		"ADJUSTMENT_TYPE_SPLIT_ADJUSTMENT":  2,
		"ADJUSTMENT_TYPE_OFFSET_ADJUSTMENT": 3,
		"ADJUSTMENT_TYPE_PHASE_EXTENSION":   4,
		"ADJUSTMENT_TYPE_PHASE_TRUNCATION":  5,
		"ADJUSTMENT_TYPE_PLAN_CHANGE":       6,
		"ADJUSTMENT_TYPE_OTHER":             7,
	}
)

func (x AdjustmentType) Enum() *AdjustmentType {
	p := new(AdjustmentType)
	*p = x
	return p
}

func (x AdjustmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdjustmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_signal_control_v1_events_proto_enumTypes[3].Descriptor()
}

func (AdjustmentType) Type() protoreflect.EnumType {
	return &file_openits_signal_control_v1_events_proto_enumTypes[3]
}

func (x AdjustmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdjustmentType.Descriptor instead.
func (AdjustmentType) EnumDescriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{3}
}

type DenialReason int32

const (
	DenialReason_DENIAL_REASON_UNSPECIFIED              DenialReason = 0
	DenialReason_DENIAL_REASON_RESERVICE_LOCK           DenialReason = 1
	DenialReason_DENIAL_REASON_COORD_CONSTRAINT         DenialReason = 2
	DenialReason_DENIAL_REASON_HIGHER_PRIORITY_CONFLICT DenialReason = 3
	DenialReason_DENIAL_REASON_DISABLED                 DenialReason = 4
	DenialReason_DENIAL_REASON_OTHER                    DenialReason = 5
)

// Enum value maps for DenialReason.
var (
	DenialReason_name = map[int32]string{
		0: "DENIAL_REASON_UNSPECIFIED",
		1: "DENIAL_REASON_RESERVICE_LOCK",
		2: "DENIAL_REASON_COORD_CONSTRAINT",
		3: "DENIAL_REASON_HIGHER_PRIORITY_CONFLICT",
		4: "DENIAL_REASON_DISABLED",
		5: "DENIAL_REASON_OTHER",
	}
	DenialReason_value = map[string]int32{
		"DENIAL_REASON_UNSPECIFIED":              0,
		"DENIAL_REASON_RESERVICE_LOCK":           1,
		"DENIAL_REASON_COORD_CONSTRAINT":         2,
		"DENIAL_REASON_HIGHER_PRIORITY_CONFLICT": 3,
		"DENIAL_REASON_DISABLED":                 4,
		"DENIAL_REASON_OTHER":                    5,
	}
)

func (x DenialReason) Enum() *DenialReason {
	p := new(DenialReason)
	*p = x
	return p
}

func (x DenialReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DenialReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_signal_control_v1_events_proto_enumTypes[4].Descriptor()
}

func (DenialReason) Type() protoreflect.EnumType {
	return &file_openits_signal_control_v1_events_proto_enumTypes[4]
}

func (x DenialReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DenialReason.Descriptor instead.
func (DenialReason) EnumDescriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{4}
}

type ControllerFaultEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	FaultId        string                 `protobuf:"bytes,2,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	Severity       FaultSeverity          `protobuf:"varint,3,opt,name=severity,proto3,enum=openits.signal_control.v1.FaultSeverity" json:"severity,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Raised         bool                   `protobuf:"varint,5,opt,name=raised,proto3" json:"raised,omitempty"`
	FlashCause     string                 `protobuf:"bytes,10,opt,name=flash_cause,json=flashCause,proto3" json:"flash_cause,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControllerFaultEvent) Reset() {
	*x = ControllerFaultEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerFaultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerFaultEvent) ProtoMessage() {}

func (x *ControllerFaultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerFaultEvent.ProtoReflect.Descriptor instead.
func (*ControllerFaultEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ControllerFaultEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ControllerFaultEvent) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *ControllerFaultEvent) GetSeverity() FaultSeverity {
	if x != nil {
		return x.Severity
	}
	return FaultSeverity_FAULT_SEVERITY_INFO
}

func (x *ControllerFaultEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ControllerFaultEvent) GetRaised() bool {
	if x != nil {
		return x.Raised
	}
	return false
}

func (x *ControllerFaultEvent) GetFlashCause() string {
	if x != nil {
		return x.FlashCause
	}
	return ""
}

func (x *ControllerFaultEvent) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *ControllerFaultEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ControllerFaultEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ControllerFaultEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControllerFaultEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ControllerFaultEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type CoordinationChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	NewValue       int32                  `protobuf:"varint,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	SplitNumber    uint32                 `protobuf:"varint,4,opt,name=split_number,json=splitNumber,proto3" json:"split_number,omitempty"`
	PreviousValue  int32                  `protobuf:"varint,5,opt,name=previous_value,json=previousValue,proto3" json:"previous_value,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoordinationChange) Reset() {
	*x = CoordinationChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinationChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinationChange) ProtoMessage() {}

func (x *CoordinationChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinationChange.ProtoReflect.Descriptor instead.
func (*CoordinationChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinationChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CoordinationChange) GetNewValue() int32 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

func (x *CoordinationChange) GetSplitNumber() uint32 {
	if x != nil {
		return x.SplitNumber
	}
	return 0
}

func (x *CoordinationChange) GetPreviousValue() int32 {
	if x != nil {
		return x.PreviousValue
	}
	return 0
}

func (x *CoordinationChange) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *CoordinationChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CoordinationChange) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CoordinationChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CoordinationChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CoordinationChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type DetectorReport struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Kind              string                    `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	IntervalStart     *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=interval_start,json=intervalStart,proto3" json:"interval_start,omitempty"`
	IntervalDurationS uint32                    `protobuf:"varint,3,opt,name=interval_duration_s,json=intervalDurationS,proto3" json:"interval_duration_s,omitempty"`
	Detector          []*DetectorReportDetector `protobuf:"bytes,4,rep,name=detector,proto3" json:"detector,omitempty"`
	ObservedBy        string                    `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             string                    `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence          uint64                    `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId    string                    `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectorReport) Reset() {
	*x = DetectorReport{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorReport) ProtoMessage() {}

func (x *DetectorReport) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorReport.ProtoReflect.Descriptor instead.
func (*DetectorReport) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DetectorReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DetectorReport) GetIntervalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalStart
	}
	return nil
}

func (x *DetectorReport) GetIntervalDurationS() uint32 {
	if x != nil {
		return x.IntervalDurationS
	}
	return 0
}

func (x *DetectorReport) GetDetector() []*DetectorReportDetector {
	if x != nil {
		return x.Detector
	}
	return nil
}

func (x *DetectorReport) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *DetectorReport) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *DetectorReport) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DetectorReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DetectorReport) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type DetectorReportDetector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorId    uint32                 `protobuf:"varint,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	PhaseServed   uint32                 `protobuf:"varint,2,opt,name=phase_served,json=phaseServed,proto3" json:"phase_served,omitempty"`
	Volume        uint32                 `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Occupancy     string                 `protobuf:"bytes,4,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorReportDetector) Reset() {
	*x = DetectorReportDetector{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorReportDetector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorReportDetector) ProtoMessage() {}

func (x *DetectorReportDetector) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorReportDetector.ProtoReflect.Descriptor instead.
func (*DetectorReportDetector) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DetectorReportDetector) GetDetectorId() uint32 {
	if x != nil {
		return x.DetectorId
	}
	return 0
}

func (x *DetectorReportDetector) GetPhaseServed() uint32 {
	if x != nil {
		return x.PhaseServed
	}
	return 0
}

func (x *DetectorReportDetector) GetVolume() uint32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *DetectorReportDetector) GetOccupancy() string {
	if x != nil {
		return x.Occupancy
	}
	return ""
}

type DetectorTransition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Channel        uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Lane           string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	Approach       string                 `protobuf:"bytes,5,opt,name=approach,proto3" json:"approach,omitempty"`
	PhaseServed    uint32                 `protobuf:"varint,6,opt,name=phase_served,json=phaseServed,proto3" json:"phase_served,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectorTransition) Reset() {
	*x = DetectorTransition{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorTransition) ProtoMessage() {}

func (x *DetectorTransition) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorTransition.ProtoReflect.Descriptor instead.
func (*DetectorTransition) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DetectorTransition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DetectorTransition) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DetectorTransition) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *DetectorTransition) GetApproach() string {
	if x != nil {
		return x.Approach
	}
	return ""
}

func (x *DetectorTransition) GetPhaseServed() uint32 {
	if x != nil {
		return x.PhaseServed
	}
	return 0
}

func (x *DetectorTransition) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *DetectorTransition) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *DetectorTransition) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DetectorTransition) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DetectorTransition) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DetectorTransition) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type OperationalStatusReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	FlashActive    bool                   `protobuf:"varint,10,opt,name=flash_active,json=flashActive,proto3" json:"flash_active,omitempty"`
	FlashCause     string                 `protobuf:"bytes,11,opt,name=flash_cause,json=flashCause,proto3" json:"flash_cause,omitempty"`
	LastModeChange *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_mode_change,json=lastModeChange,proto3" json:"last_mode_change,omitempty"`
	UptimeSeconds  uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PlanId         uint32                 `protobuf:"varint,12,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationalStatusReport) Reset() {
	*x = OperationalStatusReport{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalStatusReport) ProtoMessage() {}

func (x *OperationalStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalStatusReport.ProtoReflect.Descriptor instead.
func (*OperationalStatusReport) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *OperationalStatusReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperationalStatusReport) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OperationalStatusReport) GetFlashActive() bool {
	if x != nil {
		return x.FlashActive
	}
	return false
}

func (x *OperationalStatusReport) GetFlashCause() string {
	if x != nil {
		return x.FlashCause
	}
	return ""
}

func (x *OperationalStatusReport) GetLastModeChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModeChange
	}
	return nil
}

func (x *OperationalStatusReport) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *OperationalStatusReport) GetPlanId() uint32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *OperationalStatusReport) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *OperationalStatusReport) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OperationalStatusReport) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OperationalStatusReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OperationalStatusReport) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type OverlapChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	OverlapNumber  uint32                 `protobuf:"varint,2,opt,name=overlap_number,json=overlapNumber,proto3" json:"overlap_number,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OverlapChange) Reset() {
	*x = OverlapChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlapChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlapChange) ProtoMessage() {}

func (x *OverlapChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlapChange.ProtoReflect.Descriptor instead.
func (*OverlapChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *OverlapChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OverlapChange) GetOverlapNumber() uint32 {
	if x != nil {
		return x.OverlapNumber
	}
	return 0
}

func (x *OverlapChange) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *OverlapChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OverlapChange) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OverlapChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OverlapChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *OverlapChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PedestrianEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PhaseNumber     uint32                 `protobuf:"varint,2,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	DetectorChannel uint32                 `protobuf:"varint,3,opt,name=detector_channel,json=detectorChannel,proto3" json:"detector_channel,omitempty"`
	ObservedBy      string                 `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner           string                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence        uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source          *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId  string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PedestrianEvent) Reset() {
	*x = PedestrianEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedestrianEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedestrianEvent) ProtoMessage() {}

func (x *PedestrianEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedestrianEvent.ProtoReflect.Descriptor instead.
func (*PedestrianEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *PedestrianEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PedestrianEvent) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *PedestrianEvent) GetDetectorChannel() uint32 {
	if x != nil {
		return x.DetectorChannel
	}
	return 0
}

func (x *PedestrianEvent) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PedestrianEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PedestrianEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PedestrianEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PedestrianEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PedestrianEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PhaseStateChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PhaseNumber    uint32                 `protobuf:"varint,2,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	HoldActive     bool                   `protobuf:"varint,5,opt,name=hold_active,json=holdActive,proto3" json:"hold_active,omitempty"`
	CallRegistered bool                   `protobuf:"varint,6,opt,name=call_registered,json=callRegistered,proto3" json:"call_registered,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhaseStateChange) Reset() {
	*x = PhaseStateChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseStateChange) ProtoMessage() {}

func (x *PhaseStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseStateChange.ProtoReflect.Descriptor instead.
func (*PhaseStateChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PhaseStateChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PhaseStateChange) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *PhaseStateChange) GetHoldActive() bool {
	if x != nil {
		return x.HoldActive
	}
	return false
}

func (x *PhaseStateChange) GetCallRegistered() bool {
	if x != nil {
		return x.CallRegistered
	}
	return false
}

func (x *PhaseStateChange) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PhaseStateChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PhaseStateChange) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PhaseStateChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PhaseStateChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PhaseStateChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PlanApplied struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PlanId         uint32                 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	CycleLengthS   uint32                 `protobuf:"varint,3,opt,name=cycle_length_s,json=cycleLengthS,proto3" json:"cycle_length_s,omitempty"`
	OffsetS        uint32                 `protobuf:"varint,4,opt,name=offset_s,json=offsetS,proto3" json:"offset_s,omitempty"`
	SplitSet       uint32                 `protobuf:"varint,5,opt,name=split_set,json=splitSet,proto3" json:"split_set,omitempty"`
	Source         Source                 `protobuf:"varint,6,opt,name=source,proto3,enum=openits.signal_control.v1.Source" json:"source,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanApplied) Reset() {
	*x = PlanApplied{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanApplied) ProtoMessage() {}

func (x *PlanApplied) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanApplied.ProtoReflect.Descriptor instead.
func (*PlanApplied) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *PlanApplied) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PlanApplied) GetPlanId() uint32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *PlanApplied) GetCycleLengthS() uint32 {
	if x != nil {
		return x.CycleLengthS
	}
	return 0
}

func (x *PlanApplied) GetOffsetS() uint32 {
	if x != nil {
		return x.OffsetS
	}
	return 0
}

func (x *PlanApplied) GetSplitSet() uint32 {
	if x != nil {
		return x.SplitSet
	}
	return 0
}

func (x *PlanApplied) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *PlanApplied) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PlanApplied) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PlanApplied) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PlanApplied) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PlanApplied) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionActivated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  uint32                 `protobuf:"varint,8,opt,name=preempt_number,json=preemptNumber,proto3" json:"preempt_number,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionActivated) Reset() {
	*x = PreemptionActivated{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionActivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionActivated) ProtoMessage() {}

func (x *PreemptionActivated) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionActivated.ProtoReflect.Descriptor instead.
func (*PreemptionActivated) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *PreemptionActivated) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionActivated) GetPreemptNumber() uint32 {
	if x != nil {
		return x.PreemptNumber
	}
	return 0
}

func (x *PreemptionActivated) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreemptionActivated) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PreemptionActivated) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PreemptionActivated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionActivated) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PreemptionActivated) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionActivated) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionActivated) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionCleared struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  uint32                 `protobuf:"varint,8,opt,name=preempt_number,json=preemptNumber,proto3" json:"preempt_number,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId       string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionCleared) Reset() {
	*x = PreemptionCleared{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionCleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionCleared) ProtoMessage() {}

func (x *PreemptionCleared) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionCleared.ProtoReflect.Descriptor instead.
func (*PreemptionCleared) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *PreemptionCleared) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionCleared) GetPreemptNumber() uint32 {
	if x != nil {
		return x.PreemptNumber
	}
	return 0
}

func (x *PreemptionCleared) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreemptionCleared) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PreemptionCleared) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PreemptionCleared) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionCleared) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PreemptionCleared) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionCleared) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionCleared) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  uint32                 `protobuf:"varint,2,opt,name=preempt_number,json=preemptNumber,proto3" json:"preempt_number,omitempty"`
	SourceId       string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionEvent) Reset() {
	*x = PreemptionEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionEvent) ProtoMessage() {}

func (x *PreemptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionEvent.ProtoReflect.Descriptor instead.
func (*PreemptionEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *PreemptionEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionEvent) GetPreemptNumber() uint32 {
	if x != nil {
		return x.PreemptNumber
	}
	return 0
}

func (x *PreemptionEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PreemptionEvent) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *PreemptionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PreemptionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type SignalIndicationChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Channel        uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	PriorColor     string                 `protobuf:"bytes,3,opt,name=prior_color,json=priorColor,proto3" json:"prior_color,omitempty"`
	CurrentColor   string                 `protobuf:"bytes,4,opt,name=current_color,json=currentColor,proto3" json:"current_color,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalIndicationChanged) Reset() {
	*x = SignalIndicationChanged{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalIndicationChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalIndicationChanged) ProtoMessage() {}

func (x *SignalIndicationChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalIndicationChanged.ProtoReflect.Descriptor instead.
func (*SignalIndicationChanged) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *SignalIndicationChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SignalIndicationChanged) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SignalIndicationChanged) GetPriorColor() string {
	if x != nil {
		return x.PriorColor
	}
	return ""
}

func (x *SignalIndicationChanged) GetCurrentColor() string {
	if x != nil {
		return x.CurrentColor
	}
	return ""
}

func (x *SignalIndicationChanged) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *SignalIndicationChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SignalIndicationChanged) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SignalIndicationChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SignalIndicationChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type SiteInventoryReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	MainStreet     string                 `protobuf:"bytes,2,opt,name=main_street,json=mainStreet,proto3" json:"main_street,omitempty"`
	SecondStreet   string                 `protobuf:"bytes,3,opt,name=second_street,json=secondStreet,proto3" json:"second_street,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LatitudeE7     int64                  `protobuf:"varint,5,opt,name=latitude_e7,json=latitudeE7,proto3" json:"latitude_e7,omitempty"`
	LongitudeE7    int64                  `protobuf:"varint,6,opt,name=longitude_e7,json=longitudeE7,proto3" json:"longitude_e7,omitempty"`
	MapHex         string                 `protobuf:"bytes,7,opt,name=map_hex,json=mapHex,proto3" json:"map_hex,omitempty"`
	SpatHex        string                 `protobuf:"bytes,8,opt,name=spat_hex,json=spatHex,proto3" json:"spat_hex,omitempty"`
	MapMessageId   uint32                 `protobuf:"varint,9,opt,name=map_message_id,json=mapMessageId,proto3" json:"map_message_id,omitempty"`
	SpatMessageId  uint32                 `protobuf:"varint,10,opt,name=spat_message_id,json=spatMessageId,proto3" json:"spat_message_id,omitempty"`
	PhaseApproach  []*PhaseApproach       `protobuf:"bytes,11,rep,name=phase_approach,json=phaseApproach,proto3" json:"phase_approach,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,13,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,15,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SiteInventoryReport) Reset() {
	*x = SiteInventoryReport{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteInventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteInventoryReport) ProtoMessage() {}

func (x *SiteInventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteInventoryReport.ProtoReflect.Descriptor instead.
func (*SiteInventoryReport) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *SiteInventoryReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SiteInventoryReport) GetMainStreet() string {
	if x != nil {
		return x.MainStreet
	}
	return ""
}

func (x *SiteInventoryReport) GetSecondStreet() string {
	if x != nil {
		return x.SecondStreet
	}
	return ""
}

func (x *SiteInventoryReport) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SiteInventoryReport) GetLatitudeE7() int64 {
	if x != nil {
		return x.LatitudeE7
	}
	return 0
}

func (x *SiteInventoryReport) GetLongitudeE7() int64 {
	if x != nil {
		return x.LongitudeE7
	}
	return 0
}

func (x *SiteInventoryReport) GetMapHex() string {
	if x != nil {
		return x.MapHex
	}
	return ""
}

func (x *SiteInventoryReport) GetSpatHex() string {
	if x != nil {
		return x.SpatHex
	}
	return ""
}

func (x *SiteInventoryReport) GetMapMessageId() uint32 {
	if x != nil {
		return x.MapMessageId
	}
	return 0
}

func (x *SiteInventoryReport) GetSpatMessageId() uint32 {
	if x != nil {
		return x.SpatMessageId
	}
	return 0
}

func (x *SiteInventoryReport) GetPhaseApproach() []*PhaseApproach {
	if x != nil {
		return x.PhaseApproach
	}
	return nil
}

func (x *SiteInventoryReport) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *SiteInventoryReport) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *SiteInventoryReport) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SiteInventoryReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SiteInventoryReport) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PhaseApproach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhaseNumber   uint32                 `protobuf:"varint,1,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	Approach      string                 `protobuf:"bytes,2,opt,name=approach,proto3" json:"approach,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseApproach) Reset() {
	*x = PhaseApproach{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseApproach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseApproach) ProtoMessage() {}

func (x *PhaseApproach) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseApproach.ProtoReflect.Descriptor instead.
func (*PhaseApproach) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{15}
}

func (x *PhaseApproach) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *PhaseApproach) GetApproach() string {
	if x != nil {
		return x.Approach
	}
	return ""
}

type TsamModeChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Prior          TsamEngagementState    `protobuf:"varint,2,opt,name=prior,proto3,enum=openits.signal_control.v1.TsamEngagementState" json:"prior,omitempty"`
	Current        TsamEngagementState    `protobuf:"varint,3,opt,name=current,proto3,enum=openits.signal_control.v1.TsamEngagementState" json:"current,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TsamModeChanged) Reset() {
	*x = TsamModeChanged{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsamModeChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsamModeChanged) ProtoMessage() {}

func (x *TsamModeChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsamModeChanged.ProtoReflect.Descriptor instead.
func (*TsamModeChanged) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{16}
}

func (x *TsamModeChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TsamModeChanged) GetPrior() TsamEngagementState {
	if x != nil {
		return x.Prior
	}
	return TsamEngagementState_TSAM_ENGAGEMENT_STATE_UNSPECIFIED
}

func (x *TsamModeChanged) GetCurrent() TsamEngagementState {
	if x != nil {
		return x.Current
	}
	return TsamEngagementState_TSAM_ENGAGEMENT_STATE_UNSPECIFIED
}

func (x *TsamModeChanged) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TsamModeChanged) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *TsamModeChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TsamModeChanged) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TsamModeChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TsamModeChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TsamModeChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TsamRecommendationApplied struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	RecommendationId string                 `protobuf:"bytes,2,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	AdjustmentType   AdjustmentType         `protobuf:"varint,3,opt,name=adjustment_type,json=adjustmentType,proto3,enum=openits.signal_control.v1.AdjustmentType" json:"adjustment_type,omitempty"`
	MagnitudeSeconds string                 `protobuf:"bytes,4,opt,name=magnitude_seconds,json=magnitudeSeconds,proto3" json:"magnitude_seconds,omitempty"`
	PhaseNumber      uint32                 `protobuf:"varint,5,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	Rationale        string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"`
	ObservedBy       string                 `protobuf:"bytes,9,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner            string                 `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence         uint64                 `protobuf:"varint,11,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source           *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId   string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TsamRecommendationApplied) Reset() {
	*x = TsamRecommendationApplied{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsamRecommendationApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsamRecommendationApplied) ProtoMessage() {}

func (x *TsamRecommendationApplied) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsamRecommendationApplied.ProtoReflect.Descriptor instead.
func (*TsamRecommendationApplied) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{17}
}

func (x *TsamRecommendationApplied) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TsamRecommendationApplied) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *TsamRecommendationApplied) GetAdjustmentType() AdjustmentType {
	if x != nil {
		return x.AdjustmentType
	}
	return AdjustmentType_ADJUSTMENT_TYPE_UNSPECIFIED
}

func (x *TsamRecommendationApplied) GetMagnitudeSeconds() string {
	if x != nil {
		return x.MagnitudeSeconds
	}
	return ""
}

func (x *TsamRecommendationApplied) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *TsamRecommendationApplied) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *TsamRecommendationApplied) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *TsamRecommendationApplied) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TsamRecommendationApplied) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TsamRecommendationApplied) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TsamRecommendationApplied) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TsamRecommendationApplied) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TspEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	TspNumber         uint32                 `protobuf:"varint,10,opt,name=tsp_number,json=tspNumber,proto3" json:"tsp_number,omitempty"`
	VehicleId         string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	PriorityClass     uint32                 `protobuf:"varint,4,opt,name=priority_class,json=priorityClass,proto3" json:"priority_class,omitempty"`
	AdjustmentSeconds string                 `protobuf:"bytes,5,opt,name=adjustment_seconds,json=adjustmentSeconds,proto3" json:"adjustment_seconds,omitempty"`
	DenialReason      DenialReason           `protobuf:"varint,11,opt,name=denial_reason,json=denialReason,proto3,enum=openits.signal_control.v1.DenialReason" json:"denial_reason,omitempty"`
	ObservedBy        string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence          uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source            *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId    string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TspEvent) Reset() {
	*x = TspEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TspEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TspEvent) ProtoMessage() {}

func (x *TspEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TspEvent.ProtoReflect.Descriptor instead.
func (*TspEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{18}
}

func (x *TspEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TspEvent) GetTspNumber() uint32 {
	if x != nil {
		return x.TspNumber
	}
	return 0
}

func (x *TspEvent) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *TspEvent) GetPriorityClass() uint32 {
	if x != nil {
		return x.PriorityClass
	}
	return 0
}

func (x *TspEvent) GetAdjustmentSeconds() string {
	if x != nil {
		return x.AdjustmentSeconds
	}
	return ""
}

func (x *TspEvent) GetDenialReason() DenialReason {
	if x != nil {
		return x.DenialReason
	}
	return DenialReason_DENIAL_REASON_UNSPECIFIED
}

func (x *TspEvent) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *TspEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TspEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TspEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TspEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TspEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type UnmappedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,3,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,6,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnmappedEvent) Reset() {
	*x = UnmappedEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmappedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmappedEvent) ProtoMessage() {}

func (x *UnmappedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmappedEvent.ProtoReflect.Descriptor instead.
func (*UnmappedEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{19}
}

func (x *UnmappedEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UnmappedEvent) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *UnmappedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *UnmappedEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UnmappedEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UnmappedEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *UnmappedEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

var File_openits_signal_control_v1_events_proto protoreflect.FileDescriptor

const file_openits_signal_control_v1_events_proto_rawDesc = "" +
	"\n" +
	"&openits/signal_control/v1/events.proto\x12\x19openits.signal_control.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1copenits/types/v1/types.proto\"\xd6\x03\n" +
	"\x14ControllerFaultEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x19\n" +
	"\bfault_id\x18\x02 \x01(\tR\afaultId\x12D\n" +
	"\bseverity\x18\x03 \x01(\x0e2(.openits.signal_control.v1.FaultSeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06raised\x18\x05 \x01(\bR\x06raised\x12\x1f\n" +
	"\vflash_cause\x18\n" +
	" \x01(\tR\n" +
	"flashCause\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xff\x02\n" +
	"\x12CoordinationChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1b\n" +
	"\tnew_value\x18\x03 \x01(\x05R\bnewValue\x12!\n" +
	"\fsplit_number\x18\x04 \x01(\rR\vsplitNumber\x12%\n" +
	"\x0eprevious_value\x18\x05 \x01(\x05R\rpreviousValue\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xa0\x03\n" +
	"\x0eDetectorReport\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12A\n" +
	"\x0einterval_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rintervalStart\x12.\n" +
	"\x13interval_duration_s\x18\x03 \x01(\rR\x11intervalDurationS\x12M\n" +
	"\bdetector\x18\x04 \x03(\v21.openits.signal_control.v1.DetectorReportDetectorR\bdetector\x12\x1f\n" +
	"\vobserved_by\x18\x06 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\x92\x01\n" +
	"\x16DetectorReportDetector\x12\x1f\n" +
	"\vdetector_id\x18\x01 \x01(\rR\n" +
	"detectorId\x12!\n" +
	"\fphase_served\x18\x02 \x01(\rR\vphaseServed\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\rR\x06volume\x12\x1c\n" +
	"\toccupancy\x18\x04 \x01(\tR\toccupancy\"\x85\x03\n" +
	"\x12DetectorTransition\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\x12\x1a\n" +
	"\bapproach\x18\x05 \x01(\tR\bapproach\x12!\n" +
	"\fphase_served\x18\x06 \x01(\rR\vphaseServed\x12\x1f\n" +
	"\vobserved_by\x18\b \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xc5\x03\n" +
	"\x17OperationalStatusReport\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fflash_active\x18\n" +
	" \x01(\bR\vflashActive\x12\x1f\n" +
	"\vflash_cause\x18\v \x01(\tR\n" +
	"flashCause\x12D\n" +
	"\x10last_mode_change\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastModeChange\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12\x17\n" +
	"\aplan_id\x18\f \x01(\rR\x06planId\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xba\x02\n" +
	"\rOverlapChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0eoverlap_number\x18\x02 \x01(\rR\roverlapNumber\x12\x1f\n" +
	"\vobserved_by\x18\x05 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xe3\x02\n" +
	"\x0fPedestrianEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12!\n" +
	"\fphase_number\x18\x02 \x01(\rR\vphaseNumber\x12)\n" +
	"\x10detector_channel\x18\x03 \x01(\rR\x0fdetectorChannel\x12\x1f\n" +
	"\vobserved_by\x18\x06 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\x83\x03\n" +
	"\x10PhaseStateChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12!\n" +
	"\fphase_number\x18\x02 \x01(\rR\vphaseNumber\x12\x1f\n" +
	"\vhold_active\x18\x05 \x01(\bR\n" +
	"holdActive\x12'\n" +
	"\x0fcall_registered\x18\x06 \x01(\bR\x0ecallRegistered\x12\x1f\n" +
	"\vobserved_by\x18\b \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\x8d\x03\n" +
	"\vPlanApplied\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\rR\x06planId\x12$\n" +
	"\x0ecycle_length_s\x18\x03 \x01(\rR\fcycleLengthS\x12\x19\n" +
	"\boffset_s\x18\x04 \x01(\rR\aoffsetS\x12\x1b\n" +
	"\tsplit_set\x18\x05 \x01(\rR\bsplitSet\x129\n" +
	"\x06source\x18\x06 \x01(\x0e2!.openits.signal_control.v1.SourceR\x06source\x12\x1f\n" +
	"\vobserved_by\x18\b \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xf1\x02\n" +
	"\x13PreemptionActivated\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0epreempt_number\x18\b \x01(\rR\rpreemptNumber\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vobserved_by\x18\x05 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xef\x02\n" +
	"\x11PreemptionCleared\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0epreempt_number\x18\b \x01(\rR\rpreemptNumber\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vobserved_by\x18\x05 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xd9\x02\n" +
	"\x0fPreemptionEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0epreempt_number\x18\x02 \x01(\rR\rpreemptNumber\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vobserved_by\x18\x06 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xc7\x02\n" +
	"\x17SignalIndicationChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x1f\n" +
	"\vprior_color\x18\x03 \x01(\tR\n" +
	"priorColor\x12#\n" +
	"\rcurrent_color\x18\x04 \x01(\tR\fcurrentColor\x12\x1f\n" +
	"\vobserved_by\x18\x06 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xe2\x04\n" +
	"\x13SiteInventoryReport\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1f\n" +
	"\vmain_street\x18\x02 \x01(\tR\n" +
	"mainStreet\x12#\n" +
	"\rsecond_street\x18\x03 \x01(\tR\fsecondStreet\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlatitude_e7\x18\x05 \x01(\x03R\n" +
	"latitudeE7\x12!\n" +
	"\flongitude_e7\x18\x06 \x01(\x03R\vlongitudeE7\x12\x17\n" +
	"\amap_hex\x18\a \x01(\tR\x06mapHex\x12\x19\n" +
	"\bspat_hex\x18\b \x01(\tR\aspatHex\x12$\n" +
	"\x0emap_message_id\x18\t \x01(\rR\fmapMessageId\x12&\n" +
	"\x0fspat_message_id\x18\n" +
	" \x01(\rR\rspatMessageId\x12O\n" +
	"\x0ephase_approach\x18\v \x03(\v2(.openits.signal_control.v1.PhaseApproachR\rphaseApproach\x12\x1f\n" +
	"\vobserved_by\x18\r \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x0e \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\x0f \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"N\n" +
	"\rPhaseApproach\x12!\n" +
	"\fphase_number\x18\x01 \x01(\rR\vphaseNumber\x12\x1a\n" +
	"\bapproach\x18\x02 \x01(\tR\bapproach\"\xbd\x03\n" +
	"\x0fTsamModeChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12D\n" +
	"\x05prior\x18\x02 \x01(\x0e2..openits.signal_control.v1.TsamEngagementStateR\x05prior\x12H\n" +
	"\acurrent\x18\x03 \x01(\x0e2..openits.signal_control.v1.TsamEngagementStateR\acurrent\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\x8e\x04\n" +
	"\x19TsamRecommendationApplied\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12+\n" +
	"\x11recommendation_id\x18\x02 \x01(\tR\x10recommendationId\x12R\n" +
	"\x0fadjustment_type\x18\x03 \x01(\x0e2).openits.signal_control.v1.AdjustmentTypeR\x0eadjustmentType\x12+\n" +
	"\x11magnitude_seconds\x18\x04 \x01(\tR\x10magnitudeSeconds\x12!\n" +
	"\fphase_number\x18\x05 \x01(\rR\vphaseNumber\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\x12\x1f\n" +
	"\vobserved_by\x18\t \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\n" +
	" \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\v \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\xf0\x03\n" +
	"\bTspEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"tsp_number\x18\n" +
	" \x01(\rR\ttspNumber\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tR\tvehicleId\x12%\n" +
	"\x0epriority_class\x18\x04 \x01(\rR\rpriorityClass\x12-\n" +
	"\x12adjustment_seconds\x18\x05 \x01(\tR\x11adjustmentSeconds\x12L\n" +
	"\rdenial_reason\x18\v \x01(\x0e2'.openits.signal_control.v1.DenialReasonR\fdenialReason\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\"\x93\x02\n" +
	"\rUnmappedEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1f\n" +
	"\vobserved_by\x18\x03 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x06 \x01(\tR\x0esourceDeviceId*\x95\x01\n" +
	"\rFaultSeverity\x12\x17\n" +
	"\x13FAULT_SEVERITY_INFO\x10\x00\x12\x1a\n" +
	"\x16FAULT_SEVERITY_WARNING\x10\x01\x12\x18\n" +
	"\x14FAULT_SEVERITY_MINOR\x10\x02\x12\x18\n" +
	"\x14FAULT_SEVERITY_MAJOR\x10\x03\x12\x1b\n" +
	"\x17FAULT_SEVERITY_CRITICAL\x10\x04*v\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSOURCE_SCHEDULE\x10\x01\x12\x13\n" +
	"\x0fSOURCE_OPERATOR\x10\x02\x12\x13\n" +
	"\x0fSOURCE_ADAPTIVE\x10\x03\x12\x15\n" +
	"\x11SOURCE_PREEMPTION\x10\x04*\xcb\x01\n" +
	"\x13TsamEngagementState\x12%\n" +
	"!TSAM_ENGAGEMENT_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTSAM_ENGAGEMENT_STATE_DISABLED\x10\x01\x12\"\n" +
	"\x1eTSAM_ENGAGEMENT_STATE_ADVISORY\x10\x02\x12 \n" +
	"\x1cTSAM_ENGAGEMENT_STATE_ACTIVE\x10\x03\x12#\n" +
	"\x1fTSAM_ENGAGEMENT_STATE_SUSPENDED\x10\x04*\xa7\x02\n" +
	"\x0eAdjustmentType\x12\x1f\n" +
	"\x1bADJUSTMENT_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cADJUSTMENT_TYPE_CYCLE_LENGTH\x10\x01\x12$\n" +
	" ADJUSTMENT_TYPE_SPLIT_ADJUSTMENT\x10\x02\x12%\n" +
	"!ADJUSTMENT_TYPE_OFFSET_ADJUSTMENT\x10\x03\x12#\n" +
	"\x1fADJUSTMENT_TYPE_PHASE_EXTENSION\x10\x04\x12$\n" +
	" ADJUSTMENT_TYPE_PHASE_TRUNCATION\x10\x05\x12\x1f\n" +
	"\x1bADJUSTMENT_TYPE_PLAN_CHANGE\x10\x06\x12\x19\n" +
	"\x15ADJUSTMENT_TYPE_OTHER\x10\a*\xd4\x01\n" +
	"\fDenialReason\x12\x1d\n" +
	"\x19DENIAL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cDENIAL_REASON_RESERVICE_LOCK\x10\x01\x12\"\n" +
	"\x1eDENIAL_REASON_COORD_CONSTRAINT\x10\x02\x12*\n" +
	"&DENIAL_REASON_HIGHER_PRIORITY_CONFLICT\x10\x03\x12\x1a\n" +
	"\x16DENIAL_REASON_DISABLED\x10\x04\x12\x17\n" +
	"\x13DENIAL_REASON_OTHER\x10\x05BXZVgithub.com/Vikasa2M/openits-models/pkg/proto/openits/signal_control/v1;signalcontrolv1b\x06proto3"

var (
	file_openits_signal_control_v1_events_proto_rawDescOnce sync.Once
	file_openits_signal_control_v1_events_proto_rawDescData []byte
)

func file_openits_signal_control_v1_events_proto_rawDescGZIP() []byte {
	file_openits_signal_control_v1_events_proto_rawDescOnce.Do(func() {
		file_openits_signal_control_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_signal_control_v1_events_proto_rawDesc), len(file_openits_signal_control_v1_events_proto_rawDesc)))
	})
	return file_openits_signal_control_v1_events_proto_rawDescData
}

var file_openits_signal_control_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openits_signal_control_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_openits_signal_control_v1_events_proto_goTypes = []any{
	(FaultSeverity)(0),                // 0: openits.signal_control.v1.FaultSeverity
	(Source)(0),                       // 1: openits.signal_control.v1.Source
	(TsamEngagementState)(0),          // 2: openits.signal_control.v1.TsamEngagementState
	(AdjustmentType)(0),               // 3: openits.signal_control.v1.AdjustmentType
	(DenialReason)(0),                 // 4: openits.signal_control.v1.DenialReason
	(*ControllerFaultEvent)(nil),      // 5: openits.signal_control.v1.ControllerFaultEvent
	(*CoordinationChange)(nil),        // 6: openits.signal_control.v1.CoordinationChange
	(*DetectorReport)(nil),            // 7: openits.signal_control.v1.DetectorReport
	(*DetectorReportDetector)(nil),    // 8: openits.signal_control.v1.DetectorReportDetector
	(*DetectorTransition)(nil),        // 9: openits.signal_control.v1.DetectorTransition
	(*OperationalStatusReport)(nil),   // 10: openits.signal_control.v1.OperationalStatusReport
	(*OverlapChange)(nil),             // 11: openits.signal_control.v1.OverlapChange
	(*PedestrianEvent)(nil),           // 12: openits.signal_control.v1.PedestrianEvent
	(*PhaseStateChange)(nil),          // 13: openits.signal_control.v1.PhaseStateChange
	(*PlanApplied)(nil),               // 14: openits.signal_control.v1.PlanApplied
	(*PreemptionActivated)(nil),       // 15: openits.signal_control.v1.PreemptionActivated
	(*PreemptionCleared)(nil),         // 16: openits.signal_control.v1.PreemptionCleared
	(*PreemptionEvent)(nil),           // 17: openits.signal_control.v1.PreemptionEvent
	(*SignalIndicationChanged)(nil),   // 18: openits.signal_control.v1.SignalIndicationChanged
	(*SiteInventoryReport)(nil),       // 19: openits.signal_control.v1.SiteInventoryReport
	(*PhaseApproach)(nil),             // 20: openits.signal_control.v1.PhaseApproach
	(*TsamModeChanged)(nil),           // 21: openits.signal_control.v1.TsamModeChanged
	(*TsamRecommendationApplied)(nil), // 22: openits.signal_control.v1.TsamRecommendationApplied
	(*TspEvent)(nil),                  // 23: openits.signal_control.v1.TspEvent
	(*UnmappedEvent)(nil),             // 24: openits.signal_control.v1.UnmappedEvent
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
	(*v1.WireSource)(nil),             // 26: openits.types.v1.WireSource
}
var file_openits_signal_control_v1_events_proto_depIdxs = []int32{
	0,  // 0: openits.signal_control.v1.ControllerFaultEvent.severity:type_name -> openits.signal_control.v1.FaultSeverity
	25, // 1: openits.signal_control.v1.ControllerFaultEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 2: openits.signal_control.v1.ControllerFaultEvent.source:type_name -> openits.types.v1.WireSource
	25, // 3: openits.signal_control.v1.CoordinationChange.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 4: openits.signal_control.v1.CoordinationChange.source:type_name -> openits.types.v1.WireSource
	25, // 5: openits.signal_control.v1.DetectorReport.interval_start:type_name -> google.protobuf.Timestamp
	8,  // 6: openits.signal_control.v1.DetectorReport.detector:type_name -> openits.signal_control.v1.DetectorReportDetector
	25, // 7: openits.signal_control.v1.DetectorReport.occurred_at:type_name -> google.protobuf.Timestamp
	25, // 8: openits.signal_control.v1.DetectorTransition.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 9: openits.signal_control.v1.DetectorTransition.source:type_name -> openits.types.v1.WireSource
	25, // 10: openits.signal_control.v1.OperationalStatusReport.last_mode_change:type_name -> google.protobuf.Timestamp
	25, // 11: openits.signal_control.v1.OperationalStatusReport.occurred_at:type_name -> google.protobuf.Timestamp
	25, // 12: openits.signal_control.v1.OverlapChange.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 13: openits.signal_control.v1.OverlapChange.source:type_name -> openits.types.v1.WireSource
	25, // 14: openits.signal_control.v1.PedestrianEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 15: openits.signal_control.v1.PedestrianEvent.source:type_name -> openits.types.v1.WireSource
	25, // 16: openits.signal_control.v1.PhaseStateChange.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 17: openits.signal_control.v1.PhaseStateChange.source:type_name -> openits.types.v1.WireSource
	1,  // 18: openits.signal_control.v1.PlanApplied.source:type_name -> openits.signal_control.v1.Source
	25, // 19: openits.signal_control.v1.PlanApplied.occurred_at:type_name -> google.protobuf.Timestamp
	25, // 20: openits.signal_control.v1.PreemptionActivated.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 21: openits.signal_control.v1.PreemptionActivated.source:type_name -> openits.types.v1.WireSource
	25, // 22: openits.signal_control.v1.PreemptionCleared.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 23: openits.signal_control.v1.PreemptionCleared.source:type_name -> openits.types.v1.WireSource
	25, // 24: openits.signal_control.v1.PreemptionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 25: openits.signal_control.v1.PreemptionEvent.source:type_name -> openits.types.v1.WireSource
	25, // 26: openits.signal_control.v1.SignalIndicationChanged.occurred_at:type_name -> google.protobuf.Timestamp
	20, // 27: openits.signal_control.v1.SiteInventoryReport.phase_approach:type_name -> openits.signal_control.v1.PhaseApproach
	25, // 28: openits.signal_control.v1.SiteInventoryReport.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 29: openits.signal_control.v1.TsamModeChanged.prior:type_name -> openits.signal_control.v1.TsamEngagementState
	2,  // 30: openits.signal_control.v1.TsamModeChanged.current:type_name -> openits.signal_control.v1.TsamEngagementState
	25, // 31: openits.signal_control.v1.TsamModeChanged.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 32: openits.signal_control.v1.TsamModeChanged.source:type_name -> openits.types.v1.WireSource
	3,  // 33: openits.signal_control.v1.TsamRecommendationApplied.adjustment_type:type_name -> openits.signal_control.v1.AdjustmentType
	25, // 34: openits.signal_control.v1.TsamRecommendationApplied.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 35: openits.signal_control.v1.TsamRecommendationApplied.source:type_name -> openits.types.v1.WireSource
	4,  // 36: openits.signal_control.v1.TspEvent.denial_reason:type_name -> openits.signal_control.v1.DenialReason
	25, // 37: openits.signal_control.v1.TspEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 38: openits.signal_control.v1.TspEvent.source:type_name -> openits.types.v1.WireSource
	25, // 39: openits.signal_control.v1.UnmappedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	26, // 40: openits.signal_control.v1.UnmappedEvent.source:type_name -> openits.types.v1.WireSource
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_openits_signal_control_v1_events_proto_init() }
func file_openits_signal_control_v1_events_proto_init() {
	if File_openits_signal_control_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_signal_control_v1_events_proto_rawDesc), len(file_openits_signal_control_v1_events_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_signal_control_v1_events_proto_goTypes,
		DependencyIndexes: file_openits_signal_control_v1_events_proto_depIdxs,
		EnumInfos:         file_openits_signal_control_v1_events_proto_enumTypes,
		MessageInfos:      file_openits_signal_control_v1_events_proto_msgTypes,
	}.Build()
	File_openits_signal_control_v1_events_proto = out.File
	file_openits_signal_control_v1_events_proto_goTypes = nil
	file_openits_signal_control_v1_events_proto_depIdxs = nil
}
